name: "Work flow to run tests for intermine boot"
on: push

jobs:
    build:
        name: Setup intermine boot
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: ./actions
            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install intermine_boot
              run: "python3 -m pip install --upgrade pip setuptools wheel"
              run: "python3 -m pip install --editable ."
            - name: Run intermine boot
              run: "intermine_boot start local"
